### ISSUE TITLE
极验3和极验2的加密算法是不是相同的？

### ISSUE THREAD

**Issue by mengpengfei** [Kevin-Cherish/geetest#3]

**Comment by Kevin-Cherish** [comment]
不同。https://www.huxiu.com/

**Comment by mengpengfei** [comment]
你后面的网址什么意思

**Comment by mengpengfei** [comment]
哪里有写极验三识别相关的文章吗

**Comment by Kevin-Cherish** [comment]
极验验证二代的例子。虎X登陆需要验证。

**Comment by mengpengfei** [comment]
厉害，大神，佩服，有3代的那些加密算法吗

**Comment by Kevin-Cherish** [comment]
没有。暂时没时间破解。以后有时间再看看。

**Comment by mengpengfei** [comment]
这个轨迹是怎么录制的？

**Comment by Kevin-Cherish** [comment]
![image](https://user-images.githubusercontent.com/42607425/57992971-71febf80-7ae9-11e9-8229-7d9320e2ff7a.png)
F6Z这个变量就是轨迹数组。你每次拖动的时候记录下来就可以了。这个可能不是很方便。
网上应该还有其他轨迹录制方法。

**Comment by mengpengfei** [comment]
嗯嗯，还有个问题大神，你debug是怎么找到js函数入口的？

**Comment by Kevin-Cherish** [comment]
这个不好说。就我个人而言，我是在每个JS中搜索我需要的参数。然后打断点。

**Comment by mengpengfei** [comment]
嗯嗯，多谢，那个gsxt的也是极验2的吗

**Comment by Kevin-Cherish** [comment]
那个是极验验证3代。暂时搁置了。没时间写。

**Comment by mengpengfei** [comment]
厉害了大神，那个还差多少，我把那个完善下

**Comment by Kevin-Cherish** [comment]
差的有点多。你感兴趣可以自己看看。

**Comment by mengpengfei** [comment]
gsxt 需要解密的js函数有哪些？decryptCaptcha 里面全都包含了吗

**Comment by mengpengfei** [comment]
能不能指点下，极验3滑动之后 怎么找到处罚的是哪个函数，然后我开始debug

**Comment by Kevin-Cherish** [comment]
需要解密的函数都在fullpage.js里面。demo.js就是fullpage.js里面的部分js.

**Comment by mengpengfei** [comment]
能共享下demo.js吗

**Comment by Kevin-Cherish** [comment]
我们只需要w参数。js里面是对w变量进行了16进制unicode编码也就是‘\x77'。你全局搜索这个变量，在 这个变量打断点就行了。

**Comment by mengpengfei** [comment]
多谢多谢，我再研究下

**Comment by mengpengfei** [comment]
大神 我debug了一下怎么发下w参数的生成是在slide js里面

**Comment by mengpengfei** [comment]
原始轨迹是哪个变量，大神指导下

**Comment by mengpengfei** [comment]
能加我qq吗，我已经找到了，我们可以讨论下

**Comment by mengpengfei** [comment]
810679402

**Comment by mengpengfei** [comment]
三代的轨迹是这种格式的 [48, 110, 250, 252, 34, 124, 232, 98, 51, 226, 86, 186, 216, 3, 46, 209, 174, 211, 156, 99, 80, 10, 127, 160, 96, 251, 254, 150, 219, 186, 17, 55, 172, 17, 77, 186, 223, 25, 146, 213, 175, 96, 155, 197, 52, 76, 130, 101, 19, 58, 194, 169, 58, 86, 130, 188, 210, 103, 69, 176, 216, 11, 41, 6, 142, 160, 159, 114, 207, 162, 59, 64, 213, 230, 99, 135, 208, 56, 176, 6, 212, 61, 3, 186, 58, 237, 92, 123, 87, 83, 99, 204, 17, 221, 31, 248, 30, 199, 7, 69,

**Comment by Kevin-Cherish** [comment]
这个你可以自己写。我最近忙。给不了太大的建议。

**Comment by daisixuan** [comment]
想问下解密函数里的modulus哪里来的

**Comment by Kevin-Cherish** [comment]
![Screen Shot 2019-12-05 at 12 30 59](https://user-images.githubusercontent.com/42607425/70204611-2e556580-175c-11ea-9a0e-2145a29c90c5.png)

**Comment by daisixuan** [comment]
谢谢！我做的这个网址获取滑动验证码图片要先请求一个ajax页面他会判断是否需要滑动验证码，直接发滑动验证码的包他返回的不带滑动验证码图片，这个ajax里面的加密方法 和 后面ajax（带轨迹的验证码）一样吗。。楼主有没有JS调试教程推荐 我刚接触这块。。不是很懂

**Comment by daisixuan** [comment]
谢谢！我做的这个网址获取滑动验证码图片要先请求一个ajax页面他会判断是否需要滑动验证码，直接发滑动验证码的包他返回的不带滑动验证码图片，这个ajax里面的加密方法 和 后面ajax（带轨迹的加密参数）一样吗。。楼主有没有JS调试教程推荐 我刚接触这块。。不是很懂

**Comment by Kevin-Cherish** [comment]
没有。我自学的。不懂就百度，Goole。

**Comment by Kevin-Cherish** [comment]
> 谢谢！我做的这个网址获取滑动验证码图片要先请求一个ajax页面他会判断是否需要滑动验证码，直接发滑动验证码的包他返回的不带滑动验证码图片，这个ajax里面的加密方法 和 后面ajax（带轨迹的加密参数）一样吗。。楼主有没有JS调试教程推荐 我刚接触这块。。不是很懂

没有。我自学的。不懂就百度，Google。
