### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by SSSIBIR** [Kevin-Cherish/geetest#4]
open("Image/" + fullbg + ".jpg", "wb").write(requests.get("https://static.geetest.com/" +initData["fullbg"]).content)
FileNotFoundError: [Errno 2] No such file or directory:'Image/1558871413.50080820.3294908887686261.jpg'
您好，本地运行报了这个错误。请问什么原因？

**Comment by Kevin-Cherish** [comment]
在工作目录下创建个Image文件。

**Comment by SSSIBIR** [comment]
非常不好意思还得再麻烦您一下。
 t_dict = pickle.load(open('t_dict.pkl','rb'))
_pickle.UnpicklingError: the STRING opcode argument must be quoted
我是windows运行，请问为什么会这样？也没有转成Unix啊

**Comment by Kevin-Cherish** [comment]
https://stackoverflow.com/questions/45368255/error-in-loading-pickle

**Comment by SSSIBIR** [comment]
非常感谢您！
